#!/usr/bin/env python
from PIL import Image
from subprocess import call
import sys,os, glob


eqnum = 0


def makepng(latexeqn):
    global eqnum
    eqnum = eqnum+1
    chivo = "imgs/" + sys.argv[1]+str(eqnum)+".tex"
    latexfile = open("tmp.tex", "w")
    latexfile.write("\documentclass[10pt,border=1pt,convert]{standalone}\
    \\begin{document} $" + latexeqn + "$\
    \end{document}")
    latexfile.close()
    call(["latex", "--shell-escape", "tmp.tex"])
    base = os.path.basename(sys.argv[1])
    outfig = "imgs/"+os.path.splitext(base)[0]+str(eqnum)+".png"
    os.rename("tmp.png",outfig)
    return outfig


def putpng(linea):
    global eqnum
    l = linea.split("<em>")
    if (len(l) > 1):
        lineatmp=l[0]
        for l1 in l[1:]:
            l2 = l1.split("</em>")
            if l2[0][0]=='(':
                lineatmp=lineatmp+l2[0]+l2[1]
            else:
                figname = makepng(l2[0])
                img = Image.open(figname)
                height = img.size[1]
                lineatmp = lineatmp+"<img align=bottom height=\""+str(height/2)+"px\" src=\""+figname+"\">"+l2[1]
        return lineatmp
    else:
        return l[0]




for fileht in glob.glob("*.html"):
    file = open("tmp.html","w")
    with open(fileht) as f:
        content = f.readlines()
        for line in content:
            ll = putpng(line)
            file.write(ll)
    os.rename("tmp.html",sys.argv[1])
    for fl in glob.glob("tmp.*"):
        os.remove(fl)