#!/usr/bin/env python

import sys

outfile = sys.stdout

def cuenta(str,cini):
    count = cini
    for i in str:
        if (i == "(") or (i == "["):
            count += 1
        elif (i == ")") or (i == "]"):
            count -= 1
    return count

mp = 0

with open(sys.argv[1]) as f:
    content = f.readlines()

for line in content:
    l = line.split("/*v")
    if len(l) > 1:
        pos = l[1].find("*/")
        line = l[0]+l[1][0:pos] + l[1][pos + 3:]
    l = line.split(":=")
    if (len(l)>1):
        outfile.write(l[0]+'{')
        mp = 1
    else:
        if (mp>0):
            mp = cuenta(line,mp)
            if ( mp == 0 ):
                outfile.write("};")
            else:
                outfile.write(line)
        else:
            outfile.write(line)
